### PR TITLE
Add multiple lockfile support

### PR DESCRIPTION
**Pull request by halostatue**
This builds on #3.

### CODE REVIEW

**Comment by l2dy** [comment]
Could you rebase it on the latest commit?

**Comment by halostatue** [comment]
Done.

**Review by l2dy — COMMENTED** [review]
LGTM, but could you write a unit test for the multi-lockfile feature? This format is new to me, and a test could help ensure compatibility in the future.

**Comment by halostatue** [comment]
Sure. I’ll have to figure out how to do unit tests in Rust (I haven't really written Rust "in anger" in several years).

The format itself is not changing, but when I (and others) were looking at updating the Rust port, it turns out that the offline cargo vendoring for MacPorts needed the unified results from at least two different `Cargo.lock` files:

```
# use cargo2port to update cargo.crates
# cargo2port might have to be run in multiple directories
#     ${worksrcpath}
#     ${worksrcpath}/src/bootstrap
#     ${worksrcpath}/src/tools/rust-analyzer
#     ${worksrcpath}/??? for testing
#     ${worksrcpath}/src/tools/cargo (for rust-bootstrap port)
#     ${worksrcpath}/compiler/rustc_codegen_gcc (for https://github.com/rust-lang/rustc_codegen_gcc)
```

See ([rust/Portfile:276-283](https://github.com/MarcusCalhoun-Lopez/macports-ports/blob/841ff78d9ddeb401980957e7601ecf8d38b29746/lang/rust/Portfile#L276-L283)). The first two (`rust-lang/Cargo.lock` and `rust-lang/src/bootstrap/Cargo.lock`) are the only ones that I can absolutely *confirm* as required, but other required lock collections may be identified through testing.

Someone else who had done an independent update had come up with a chained `sed` output which combined multiple runs of `cargo2port`, stripping the `cargo.crates` header line from all of them, and then reinserting it on the sorted final list.

Which is what I’ve tried to do directly in rust here.

**Comment by halostatue** [comment]
- Tests have been added on the "golden file" model using the goldenfile crate.

  - This makes comparison very easy and predictable.

  - It also allows us to quickly verify that, in the case of multiple file collection and output, we have meaningful output that shows the files are sorted.

  - Six golden files (one for each alignment mode) are used for three integration test cases:

    - single file (always the current `Cargo.lock`);

    - duplicate file (always the current `Cargo.lock` specified twice); these reuse the single file golden files because there should be exactly *no* difference because of our use of the set;

    - multiple file (fixed files in the `Cargo.lock` version 3 format, pulled from `rust-lang/rust/Cargo.lock`  and `rust-lang/rust/bootstrap/Cargo.lock`. These are `multi_lockfile_one` and `multi_lockfile_two`, respectively. Hopefully this naming will prevent unnecessary Dependabot updates.

  - The golden files for the single file will have to be updated on each release where dependencies are updated.

  - The golden files for multiple files should be updated when there is a difference in the `Cargo.lock` version. We do not need to track these files.

- Split the code into two files (lib and main).

  - This rearrangement required that a couple of functions have their return type modified so that we can meaningfully use `function()?` and defer exit from the library and only have it happen in the binary.

  - Added `format_cargo_crates(Vec<Package>, AlignmentMode) -> String` to make it easier to use golden file testing. The two downsides are that no output will happen until the output is complete and that memory use will increase as we are collecting the output in a string before output.

- Added some smarts to the binary portion so that if I specify `cargo2port . bootstrap`, it will recognize that both `.` and `bootstrap` are directories and check for `./Cargo.lock` and `bootstrap/Cargo.lock`. This means you only have to specify the *directories* from the command-line, not the full path to Cargo.lock.

**Review by l2dy — APPROVED** [review]

**Pull request merged**
