### PR TITLE
feat: Read Cargo.lock from crates.io

### PR DESCRIPTION
**Pull request by halostatue**
Adds a special format for a dependency name, `crate:name@version`, which will download the requested crate version from crates.io, extract the first Cargo.lock file it finds, and parse it with cargo-lock.

This feature adds three dependencies: `reqwest`, `flate2`, and `tar`.

### CODE REVIEW

**Comment by halostatue** [comment]
This would be run as `cargo2port crate:mise@2024.8.5` and output the same data as if you cloned `jdx/mise` at the `v2024.8.5` tag and ran `cargo2port mise/Cargo.lock`, but much faster and with less command-line interaction.

**Comment by l2dy** [comment]
This adds more complexity and dependencies to the core program than I'd like. What do you think of a bash script under `contrib/` directory that chains `curl`, `tar` and `cargo2port` together as an alternative? It would be more flexible and easier to debug when something goes wrong.

**Comment by halostatue** [comment]
I understand, which is part of why I mentioned the added dependencies. I might want something that can work in a script pipeline in the future, but right now I’m more likely to maintain and use my fork of `cargo2port`.

1. Run `seaport` to get the new baseline port update.‡
2. Clone the repo.
3. Run `cargo2port repo/Cargo.lock` to get the update.
4. Remove the cloned repo.

This change removes steps 2 and 4 except on complex builds that require multiple `Cargo.lock` files be parsed (Rust itself is probably the main one here). There's no reason why `seaport` couldn't end up calling `cargo2port` or `go2port` as appropriate since it downloads the source archive in the first place, but it doesn't. That's one reason why I'm *considering* writing something that would replace `seaport`, `cargo2port`, and `go2port` in my usage (`go2port` has bigger problems because I think that the Go portgroup uses the wrong approach for dependencies, since they are all pulled from GitHub sources rather than using the Go proxy mechanism to minimize downloads, but that is an entirely *different* kettle of fish that I need to explore and seriously level up my Tcl development to resolve).

---

Within a script context, I think that supporting `-` as "read from stdin" would be the appropriate step, because what I implemented here does everything in memory (but not streamed, which would be even better on memory usage, but even more complex). That way, you could do:

```bash
curl https://crates.io/api/v1/{crate}/{version}/download | tar xz - '*/Cargo.lock' | cargo2port -
```

**Comment by l2dy** [comment]
> I'm _considering_ writing something that would replace `seaport`, `cargo2port`, and `go2port` in my usage (`go2port` has bigger problems because I think that the Go portgroup uses the wrong approach for dependencies, since they are all pulled from GitHub sources rather than using the Go proxy mechanism to minimize downloads, but that is an entirely _different_ kettle of fish that I need to explore and seriously level up my Tcl development to resolve).

In that case, cargo2port could be split into a library that can be imported, if you intend to write it in Rust.

> Within a script context, I think that supporting `-` as "read from stdin" would be the appropriate step, because what I implemented here does everything in memory (but not streamed, which would be even better on memory usage, but even more complex). That way, you could do:
> 
> ```shell
> curl https://crates.io/api/v1/{crate}/{version}/download | tar xz - '*/Cargo.lock' | cargo2port -
> ```

That's a great idea and can be reused from any application or script. Pull request is welcome!

**Comment by halostatue** [comment]
I haven't decided whether I'm going to write it in Rust, but my main goal with these changes as I said was to reduce the number of steps that I have when updating a Rust port.

Adding `-` as `read from stdin` will require some portion of these changes, but I’ll separate them out in a few days — I have a number of things I need to get done before then.

**Comment by halostatue** [comment]
I’m going to keep my branch open, but I am closing this PR as you have indicated that you prefer keeping `cargo2port` low dependency.

**Pull request closed without merging**
